Add Commands onError hook
boostercloud/booster pull request #1052
Opened 2022-04-06 14:02 UTC by gonzalogarciajaubert

## Description
Add Commands onError hook

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [x] Updated documentation accordingly

# Note: Base branch: feature/add_local_after_filter

2022-04-06 15:07 UTC, rdiaz82 approved these changes
LGTM

2022-06-16 14:21 UTC, javiertoledo commented
I don't know if I see the value in this change. Can't you handle command errors using try/catch clauses already?

2022-06-30 13:45 UTC, NickSeagull requested changes

2022-06-30 13:45 UTC, NickSeagull commented on packages/framework-core/src/booster-command-dispatcher.ts
> +      throw await applyOnErrorFunctions(e, commandEnvelope.value, commandMetadata.onError, register)
Note that here `e` can be whatever, not only `Error`

2023-02-23 12:20 UTC, javiertoledo commented
Closing, as this feature was replaced by the global error handler

2023-02-23 12:20 UTC, closed without merging