Migrate snapshot before reduce it and persist it if needed
boostercloud/booster pull request #1094
Opened 2022-06-01 09:22 UTC by gonzalogarciajaubert

## Description
Migrate snapshot before reduce it and persist it if needed

## Checks
- [X] Project Builds
- [X] Project passes tests and checks
- [ ] Updated documentation accordingly

2022-06-03 11:20 UTC, javiertoledo approved these changes
LGTM. Just left a minor change proposal

2022-06-29 10:20 UTC, NickSeagull requested changes

2022-06-29 10:20 UTC, NickSeagull commented on packages/framework-core/src/services/event-store.ts
> +  }
Let's avoid using `null`, it is considered bad practice. Use `undefined` instead

```suggestion
  private async migrateSnapshot(eventEnvelope?: EventEnvelope): Promise<EventEnvelope | undefined> {
    if (eventEnvelope) {
      const migratedEventEnvelope = await this.migrator.migrate(eventEnvelope)
      if (eventEnvelope.version !== migratedEventEnvelope.version) {
        await this.storeSnapshot(migratedEventEnvelope)
      }
      return migratedEventEnvelope
    }
    return undefined
  }
```

2022-06-29 10:20 UTC, NickSeagull commented on packages/framework-core/src/services/event-store.ts
> +      const snapshotInstance = latestSnapshot ? createInstance(entityMetadata.class, latestSnapshot.value) : null
```suggestion
      const snapshotInstance = latestSnapshot ? createInstance(entityMetadata.class, latestSnapshot.value) : undefined
```

2022-06-30 10:10 UTC, closed without merging