fix(unittests): make unittests pass on Windows per issue #538
boostercloud/booster pull request #1267
Opened 2022-12-08 02:35 UTC by nicolatl

Unittests now pass on windows. Used path.join and cross-env to make commands compatible with both Windows and macOS.

@shawnzhang12 and I got 36/39 integration tests passing too, but didn't include those in this PR, to keep PRs modular. This integration work is in a fork here https://github.com/shawnzhang12/booster/commits/main.

2022-12-12 14:40 UTC, NickSeagull requested changes
Awesome! Just as a nit-pick, why `path.join` and not `path.normalize`?

2022-12-12 16:04 UTC, javiertoledo approved these changes
Great work @nicolatl!

2022-12-13 21:43 UTC, nicolatl commented
> Awesome! Just as a nit-pick, why `path.join` and not `path.normalize`?

Good point -- normalize makes more sense. I changed this where applicable a960e8cc050874f0db53265e01e122f40b9d3e9e

2022-12-13 21:48 UTC, nicolatl commented on packages/framework-provider-aws-infrastructure/package.json
> +    "test": "nyc --extension .ts mocha --forbid-only \"test/**/*.test.ts\" --timeout 600000"
Great catch -- this was my temporary solution for aws-infrastructure timeouts, which I was seeing as per issue https://github.com/boostercloud/booster/pull/1267.
A better solution could be found for that issue, or in any case it should be its own PR.

2022-12-14 12:02 UTC, NickSeagull approved these changes

2022-12-14 20:15 UTC, merged