feat(core): Notification events
boostercloud/booster pull request #1319
Opened 2023-01-25 13:30 UTC by NickSeagull

## Description
<Describe the purpose of this pull request>

## Changes

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [x] Updated documentation accordingly

2023-02-01 12:54 UTC, NickSeagull commented
Working on this for now

2023-02-07 12:45 UTC, NickSeagull commented
/wtd

2023-02-08 14:56 UTC, NickSeagull commented
/integration sha=c865ec2

2023-02-08 16:25 UTC, NickSeagull commented
/integration 6142022

2023-02-08 16:50 UTC, NickSeagull commented
/integration e1c76a8

2023-02-08 17:09 UTC, NickSeagull commented
/integration e1c76a8

2023-02-09 13:05 UTC, javiertoledo requested changes
Great work here, and super-useful feature! I left you some suggestions; it could be worth considering minor renames in part of the code that handles both notification and state change events to make the code clearer. Also, I think there's a way to simplify how we store notifications metadata in the `Booster.config`. Let me know your thoughts!

2023-02-09 13:05 UTC, javiertoledo commented on packages/framework-types/src/concepts/register.ts
> +    return this
Why not use the same `register.events` method to register notifications? It seems a bit confusing to me that we have a separate way to handle them when at the end of the day, they're also events... what do you think?

2023-02-13 11:40 UTC, NickSeagull commented on packages/framework-core/src/decorators/notification.ts
> +      }
The first thing could lead to the fact that there's an event that's not a notification and has no entities associated and could trigger an error.

I left the notifications, and eventToTopic and topicToEvent separated on purpose in order to make this easier to separate in the future.

Notifications and entities would have their own fields, and the other two mappings would be part of the event store module.

2023-02-13 16:44 UTC, NickSeagull commented
/integration 7cce0a2

2023-02-16 14:05 UTC, merged