documentation refactor and custom providers documentation
boostercloud/booster pull request #1333
Opened 2023-02-09 10:54 UTC by rdiaz82

## Description
This PR performs the following changes in documentation:
- Refactor in the documentation organisation specially in `Going Deep with Booster Section` and `Getting Started`
- Added a new page documenting the providers interface.

## Changes
Here is a video showing the comparison between the current documentation with all the changes introduced in this PR:
[Video PR explanation](https://www.loom.com/share/6eef7ec862134298bb23d4a76ced8011)

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [x] Updated documentation accordingly

2023-02-09 18:19 UTC, javiertoledo requested changes
Great changes! I left a few comments with suggestions. Also, I think it would be worth adding TSDoc comments to the provider interface as part od this change. It could also make sense to show the interfaces in the documentation too for clearer reference.

2023-02-09 18:19 UTC, javiertoledo commented on website/docs/10_going-deep/custom-providers.mdx
> +- **nuke**: This is method is charge of destroy all generated resources during the deploy and it is called during the nuke process.
```suggestion
- **nuke**: This is method is charge of destroy all generated resources during the deploy and it is called during the nuke process. 
- **start**: This method is used when the provider implements a server that needs to be started (i.e. the local provider)
- **synth**: This method allows you to export the infrastructure to a file (for instance, if you use the Terraform CDK, you can export the script here to run it using conventional terraform tools)
```

2023-02-09 18:19 UTC, javiertoledo commented on website/docs/10_going-deep/custom-providers.mdx
> +For the implementation of the infrastructure interface you can use any Infrastructure as Code tool provided by cloud providers or third parties.
```suggestion
The infrastructure interface just defines an adapter for Booster so the framework knows how to start any of the described processes, but you can use any Infrastructure as Code tool that has a Typescript DSL (CDK) or even call other CLI tools or scripts if you rather maintain it using a different technology.
```

2023-02-09 18:19 UTC, javiertoledo commented on website/docs/10_going-deep/custom-providers.mdx
> +The runtime interface is divided in different sections:
```suggestion
The runtime interface ([ProviderLibrary](https://github.com/boostercloud/booster/blob/main/packages/framework-types/src/provider.ts)) is divided in seven sections:
```

2023-02-10 10:44 UTC, rdiaz82 commented on website/docs/02_getting-started/coding.mdx
> +  @boostercloud/framework-provider-azure (Azure)
😆

2023-02-10 14:22 UTC, rdiaz82 commented on website/docs/03_features/09_testing.md
> +- Tests to ensure that the application behaves in the same way no matter what provider is selected.
I have moved it to the going deeper section, rather than have it inside the Features section.

2023-02-10 14:22 UTC, rdiaz82 commented on website/docs/10_going-deep/custom-providers.mdx
> +
Done :)

2023-02-13 16:56 UTC, javiertoledo approved these changes
LGTM!

2023-02-13 18:05 UTC, merged