Add clarification about Data Migrations and updated example
boostercloud/booster pull request #1358
Opened 2023-02-24 14:26 UTC by jfsagasti

2023-02-24 14:40 UTC, BorjaZarco approved these changes
LGTM! 👍

2023-02-24 17:06 UTC, javiertoledo requested changes

2023-02-24 17:06 UTC, javiertoledo commented on website/docs/10_going-deeper/data-migrations.md
> +* **Data migrations**, on the other hand, behave as background processes that can actively change the existing values in the database for existing entities and read models. They are particularly usef
Let's double check that this is true before merging this change, from what I know this feature was implemented in a vendor-agnostic way 🤔

2023-02-28 16:31 UTC, javiertoledo requested changes
@jfsagasti I've added a couple of suggestions according to our earlier conversations.

2023-02-28 16:31 UTC, javiertoledo commented on website/docs/10_going-deeper/data-migrations.md
> +* **Data migrations**, on the other hand, behave as background processes that can actively change the existing values in the database for existing entities and read models. They are particularly usef
According to the conversations we've been having about this, I'm suggesting a couple of edits:

```suggestion
* **Data migrations**, on the other hand, behave as background processes that can actively change the existing values in the database for existing entities and read models. They are particularly useful for data migrations that cannot be performed automatically with schema migrations, or for updating existing read models after a schema change.
```

2023-02-28 16:31 UTC, javiertoledo commented on website/docs/10_going-deeper/data-migrations.md
>  Here is an example of how you might use the `@DataMigration` decorator and the `Booster.migrateEntity` method to update the quantity of the first item in a cart:
```suggestion
Here is an example of how you might use the `@DataMigration` decorator and the `Booster.migrateEntity` method to update the quantity of the first item in a cart (**Notice that at the time of writing this document, the method `Booster.entitiesIDs` used in the following example is only available in the Azure provider, so you may need to approach the migration differently in AWS.**):
```

2023-09-25 15:36 UTC, javiertoledo approved these changes

2023-09-25 15:42 UTC, merged