docs(auth): Add no admin by default note
boostercloud/booster pull request #507
Opened 2020-12-16 18:09 UTC by adriangmweb

## Description
Just added a note clarification about that there is not Admin user by default.

## Changes
One line in the docs README. 

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [x] Updated documentation accordingly
 
## Additional information
[It ain't much but it's honest work](https://en.meming.world/images/en/thumb/b/be/But_It%27s_Honest_Work.jpg/300px-But_It%27s_Honest_Work.jpg)

2020-12-16 21:31 UTC, rdiaz82 approved these changes
LGTM

2020-12-17 10:01 UTC, NickSeagull requested changes

2020-12-17 10:01 UTC, NickSeagull commented on docs/README.md
> +_Note: There is not `Admin` user by default. In order to register one you need specify a sign-up method on `src/roles.ts`._
Typo

```suggestion
_Note: There is no `Admin` user by default. In order to register one you need to specify a sign-up method on `src/roles.ts`._
```

2020-12-17 16:40 UTC, NickSeagull approved these changes

2020-12-17 16:41 UTC, merged