Added some code guidelines
boostercloud/booster pull request #562
Opened 2021-01-19 16:29 UTC by javiertoledo

Upon popular request, I've added some code guidelines to `CONTRIBUTING.md`, feel free to submit your suggestions too!

2021-01-20 11:02 UTC, NickSeagull requested changes

2021-01-20 11:02 UTC, NickSeagull commented on CONTRIBUTING.md
> +}
I believe this doesnt work

2021-01-20 11:02 UTC, NickSeagull commented on CONTRIBUTING.md
> +Use `const` and immutable object when possible, otherwise, use `let`.
I'd phrase this as
```suggestion
Default to `const` and immutable objects when possible, otherwise, use `let`.
```

2021-01-21 11:11 UTC, alvaroloes approved these changes

2021-01-22 18:03 UTC, javiertoledo commented on CONTRIBUTING.md
> +}
Alright!

```suggestion
export const ModuleB = {
  functionB1: () => {...},
  functionB2: () => {...},
}
```

2021-01-26 19:10 UTC, merged