fixed Underscore _ in project name must be escaped before deploying #567
boostercloud/booster pull request #572
Opened 2021-01-21 11:43 UTC by rijusougata13

## Description
fixed Underscore _ in project name must be escaped before deploying #567

## Changes
 add a check in  assertNameIsCorrect to check for "_" in project name
## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks
- [ ] Updated documentation accordingly
 
## Additional information

2021-01-21 11:51 UTC, NickSeagull requested changes
Thanks a lot! This is super useful for the project, can you just change the little thing I pointed?

2021-01-21 11:51 UTC, NickSeagull commented on packages/cli/src/services/provider-service.ts
> +    throw new Error(`Project name cannot contain underscore(_):
I think we can omit the parentheses 😄 

```suggestion
    throw new Error(`Project name cannot contain underscore:
```

2021-01-21 12:34 UTC, NickSeagull approved these changes
Thanks! 🙏

2021-01-21 14:48 UTC, davidverdu approved these changes
Nice work! Thank you so much. One note: could you add a unit test case for your validation in this file? `packages/cli/test/services/provider-service.test.ts`. To run unit tests you can just run the command `lerna run test` (this will launch all unit tests of the project). Also, the command `lerna run integration` should pass. Thank you

2021-01-21 18:58 UTC, javiertoledo requested changes
Only missing a unit test

2021-02-01 17:13 UTC, closed without merging

2021-02-02 12:02 UTC, davidverdu commented
@alvaroloes this PR is about to fix https://github.com/boostercloud/booster/issues/567 . It only needs a unit test. However, this PR was closed before merging. Maybe for the change from master to main applied by @javiertoledo . Could you confirm the reason of this PR being closed?

2021-02-25 11:47 UTC, NickSeagull commented
@javiertoledo why the closing of this?

2021-02-25 11:47 UTC, NickSeagull commented
@davidverdu I believe this PR got closed because it got stalled

2021-02-25 12:12 UTC, davidverdu commented
@NickSeagull the issue is still open. No news from the PR creator. @rijusougata13 are you about to add the unit test to complete the PR? Or shall I complete it and merge them?

2021-02-25 13:56 UTC, rijusougata13 commented
> @NickSeagull the issue is still open. No news from the PR creator.

but @javiertoledo closed this pr

2021-02-26 09:29 UTC, javiertoledo commented
Yes, I closed it because I thought it was abandoned, sorry if that was a mistake, feel free to reopen it anytime!