Doc: Add Booster Rockets list
boostercloud/booster pull request #678
Opened 2021-03-15 18:41 UTC by Moneyba

## Description
There is currently no reference to the Booster Rockets in the documentation.

## Changes
Add a list with the current BoosterRockets

## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks
- [ ] Updated documentation accordingly
 
## Additional information

2021-03-17 19:04 UTC, javiertoledo requested changes
Just deleted a few from the list that are not public yet. Maybe we should consider publishing the file uploader one 🤔

2021-03-17 19:04 UTC, javiertoledo commented on docs/README.md
> +- [[WIP\] Kafka Integration Rocket](https://github.com/boostercloud/rocket-kafka-aws-infrastructure)
I deleted a couple of them that are not public yet :trollface: 

```suggestion
- [Authentication Booster Rocket for AWS](https://github.com/boostercloud/rocket-auth-aws-infrastructure)
- [Backup Booster Rocket for AWS](https://github.com/boostercloud/rocket-backup-aws-infrastructure)
- [Static Sites Booster Rocket for AWS](https://github.com/boostercloud/rocket-static-sites-aws-infrastructure)
```

2021-03-19 15:28 UTC, AdrianLorenzoDev approved these changes
LGTM!

2021-03-22 08:22 UTC, Moneyba commented
@javiertoledo, I made that change but I still see "changes requested" and I can't merge. Could you check if it's ok now?

2021-03-22 17:26 UTC, rdoria1 approved these changes
LGTM

2021-03-22 17:34 UTC, merged