Doc/750 add style
boostercloud/booster pull request #766
Opened 2021-04-05 08:55 UTC by Moneyba

## Description
Add style using [docsify](https://docsify.js.org/#/) 

## Changes
Restructure the documentation and add style.

## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks
- [ ] Updated documentation accordingly
 
## Additional information

2021-04-05 10:53 UTC, davidverdu commented
LGTM but, why do you delete so many lines from package-lock.json file? Another weird thing is that unit tests are not passing

2021-04-05 13:54 UTC, AdrianLorenzoDev approved these changes
LGTM!!! 🙂

2021-04-07 14:21 UTC, davidverdu commented on docs/chapters/02_getting-started.md
> +[other_profile]   Give this profile the name that works best for you
why do we have this spaces at the beginning of the sentences? " Give this profile..." in place of "Give this profile...". This repeats in many parts of the files

2021-04-07 14:22 UTC, davidverdu commented on docs/chapters/02_getting-started.md
> +###  2. First command
Anocher white space I don't understand

2021-04-07 20:09 UTC, davidverdu commented on docs/chapters/05_going-deeper.md
> +# Providers configuration
I believe here it should be `### Providers configuration`, don't you think? The doc section is being displayed wrongly in docsify due to this typo

2021-04-07 20:18 UTC, davidverdu commented on docs/chapters/02_getting-started.md
> +> You can see more details in the [Providers configuration](chapters/05_going-deeper.md#providers) section.
It should point to chapters/05_going-deeper.md#providers-configuration instead

2021-04-07 20:19 UTC, davidverdu commented on docs/chapters/02_getting-started.md
> +> You can see more details in the [Providers configuration](chapters/05_going-deeper.md#providers) section.
It should point to chapters/05_going-deeper.md#providers-configuration instead

2021-04-07 20:19 UTC, davidverdu commented on docs/chapters/02_getting-started.md
> +> You can see more details in the [Providers configuration](chapters/05_going-deeper.md#providers) section.
It should point to chapters/05_going-deeper.md#providers-configuration instead

2021-04-07 20:27 UTC, davidverdu commented on docs/chapters/03_booster-architecture.md
> +![reducer process gif](img/reducer.gif)
This image is not visualizing correctly in Docsify

2021-04-07 20:31 UTC, davidverdu commented on docs/chapters/05_going-deeper.md
> +
here I would add as originally this text, but linking to our new contributing guide:

`Contributing

If you want to start making contributions to Booster, we strongly recommend that you read our contributing guide.`

2021-04-07 20:37 UTC, davidverdu requested changes
LGTM. Good job by turning normal documentation into this amazing doc displaying! Nonetheless, I left some minor comments that should be addressed before merging

2021-04-08 09:53 UTC, davidverdu approved these changes
LGTM!

2021-04-08 10:04 UTC, merged